name: Learning Triggers
# on: workflow_dispatch
on:
  push:
    branches:
      # - feature
       - main
jobs: 
  my-trigger:
    runs-on: ubuntu-latest
    steps: 
     - name: Understand Triggers
       run: echo "push to main branch"
      