name: caller_code
on: [push]
 
jobs: 
 common_caller: 
  runs-on: ubuntu-latest
   - uses:  Tarunteja5182/workflows/blob/main/.github/workflows/common-workflow-code.yaml
     with:  
       project: 'roboshop'
       component: 'catalogue'
       environment: 'staging'