name : Hello world actions
on: [push]

jobs: 
  say_hello:    # This is the job name, which you will see in github
    runs-on: ubuntu-latest
    steps: 
      - name : My First actions
        run: echo "This is my first workflow"